# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08bd78ef21e7bbeabb4f2bce19f39f444d03dc5b986cfbfeb5d6d6a23cfca985bd6e506622eac600a22ed70d0f1d92bce720ef94100bcf8cf58d16073f58ba90

test:
  secret_key_base: 8868a2ba97199e1f857d0929a92ca2436bb6b7d885cd61737f1662b7b68d56b43a2a39426ae04151bfa3893c0e9b0d37d7beae698364ab59d026eb248d904e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
